# Generated by Django 5.2.7 on 2025-11-10 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeplugin',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proplugin',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('SYN', 'Synth'), ('CMP', 'Compressor'), ('DST', 'Distorter'), ('EFX', 'Effect')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('SYN', 'Synth'), ('CMP', 'Compressor'), ('DST', 'Distorter'), ('EFX', 'Effect')], max_length=3),
        ),
    ]
