# Generated by Django 5.2.7 on 2025-11-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('CMP', 'Compressor'), ('DAW', 'Digital Audio Workstation'), ('SYN', 'Synth'), ('DST', 'Distorter'), ('EFX', 'Effect')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('CMP', 'Compressor'), ('DAW', 'Digital Audio Workstation'), ('SYN', 'Synth'), ('DST', 'Distorter'), ('EFX', 'Effect')], max_length=3),
        ),
    ]
