# Generated by Django 5.2.7 on 2025-11-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('SYN', 'Synth'), ('CMP', 'Compressor'), ('EFX', 'Effect'), ('DAW', 'Digital Audio Workstation'), ('DST', 'Distorter')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alternativeplugin',
            name='image',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('SYN', 'Synth'), ('CMP', 'Compressor'), ('EFX', 'Effect'), ('DAW', 'Digital Audio Workstation'), ('DST', 'Distorter')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='image',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
