# Generated by Django 5.2.7 on 2025-11-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('EFX', 'Effect'), ('SYN', 'Synth'), ('CMP', 'Compressor'), ('DAW', 'Digital Audio Workstation'), ('DST', 'Distorter')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='pro_plugins', to='home.alternativeplugin'),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('EFX', 'Effect'), ('SYN', 'Synth'), ('CMP', 'Compressor'), ('DAW', 'Digital Audio Workstation'), ('DST', 'Distorter')], max_length=3),
        ),
    ]
