# Generated by Django 5.2.7 on 2025-11-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('DST', 'Distorter'), ('CMP', 'Compressor'), ('SYN', 'Synth'), ('DAW', 'Digital Audio Workstation'), ('EFX', 'Effect')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('DST', 'Distorter'), ('CMP', 'Compressor'), ('SYN', 'Synth'), ('DAW', 'Digital Audio Workstation'), ('EFX', 'Effect')], max_length=3),
        ),
    ]
