# Generated by Django 5.2.7 on 2025-11-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('DAW', 'Digital Audio Workstation'), ('EFX', 'Effect'), ('SYN', 'Synth'), ('DST', 'Distorter'), ('CMP', 'Compressor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('DAW', 'Digital Audio Workstation'), ('EFX', 'Effect'), ('SYN', 'Synth'), ('DST', 'Distorter'), ('CMP', 'Compressor')], max_length=3),
        ),
    ]
