# Generated by Django 5.2.7 on 2025-11-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser_avatar_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('DST', 'Distorter'), ('EFX', 'Effect'), ('SYN', 'Synth'), ('CMP', 'Compressor'), ('DAW', 'Digital Audio Workstation')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('DST', 'Distorter'), ('EFX', 'Effect'), ('SYN', 'Synth'), ('CMP', 'Compressor'), ('DAW', 'Digital Audio Workstation')], max_length=3),
        ),
    ]
