# Generated by Django 5.2.7 on 2025-11-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('DAW', 'Digital Audio Workstation'), ('SYN', 'Synth'), ('EFX', 'Effect'), ('DST', 'Distorter'), ('CMP', 'Compressor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alternativeplugin',
            name='image',
            field=models.ImageField(blank=True, default='/static/soundwave.jpg', null=True, upload_to='plugin_images/'),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('DAW', 'Digital Audio Workstation'), ('SYN', 'Synth'), ('EFX', 'Effect'), ('DST', 'Distorter'), ('CMP', 'Compressor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='image',
            field=models.ImageField(blank=True, default='soundwave.jpg', null=True, upload_to='plugin_images/'),
        ),
    ]
