# Generated by Django 5.2.7 on 2025-11-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('DST', 'Distorter'), ('CMP', 'Compressor'), ('DAW', 'Digital Audio Workstation'), ('EFX', 'Effect'), ('SYN', 'Synth')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alternativeplugin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plugin_images/'),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('DST', 'Distorter'), ('CMP', 'Compressor'), ('DAW', 'Digital Audio Workstation'), ('EFX', 'Effect'), ('SYN', 'Synth')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plugin_images/'),
        ),
    ]
