# Generated by Django 5.2.7 on 2025-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('SYN', 'Synth'), ('EFX', 'Effect'), ('DAW', 'Digital Audio Workstation'), ('DST', 'Distorter'), ('CMP', 'Compressor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('SYN', 'Synth'), ('EFX', 'Effect'), ('DAW', 'Digital Audio Workstation'), ('DST', 'Distorter'), ('CMP', 'Compressor')], max_length=3),
        ),
    ]
