# Generated by Django 5.2.7 on 2025-12-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('DST', 'Distorter'), ('DAW', 'Digital Audio Workstation'), ('EFX', 'Effect'), ('SYN', 'Synth'), ('CMP', 'Compressor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('DST', 'Distorter'), ('DAW', 'Digital Audio Workstation'), ('EFX', 'Effect'), ('SYN', 'Synth'), ('CMP', 'Compressor')], max_length=3),
        ),
    ]
