# Generated by Django 5.2.7 on 2025-12-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='category',
            field=models.CharField(choices=[('EFX', 'Effect'), ('SYN', 'Synth'), ('CMP', 'Compressor'), ('DST', 'Distorter'), ('DAW', 'Digital Audio Workstation')], max_length=3),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.CharField(choices=[('EFX', 'Effect'), ('SYN', 'Synth'), ('CMP', 'Compressor'), ('DST', 'Distorter'), ('DAW', 'Digital Audio Workstation')], max_length=3),
        ),
    ]
