# Generated by Django 5.2.7 on 2026-01-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeplugin',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='proplugin',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
