# Generated by Django 5.2.7 on 2026-02-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_alternativeplugin_size_alter_proplugin_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('audio_file', models.FileField(upload_to='audio_demos/')),
                ('alt_plugin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.alternativeplugin')),
                ('pro_plugin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_demos', to='home.proplugin')),
            ],
        ),
    ]
