# Generated by Django 5.2.7 on 2026-02-01 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_audiodemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodemo',
            name='audio_file',
            field=models.FileField(upload_to='audio_demos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
    ]
