# Generated by Django 5.2.7 on 2026-02-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_category_alter_alternativeplugin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proplugin',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_plugins', to='home.category'),
        ),
    ]
