# Generated by Django 5.2.7 on 2026-02-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_proplugin_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativeplugin',
            name='category',
        ),
        migrations.RemoveField(
            model_name='proplugin',
            name='category',
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'unique_together': {('parent', 'slug')},
            },
        ),
    ]
