# Generated by Django 5.2.7 on 2026-02-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_alternativeplugin_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeplugin',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_plugins', to='home.subcategory'),
        ),
        migrations.AddField(
            model_name='proplugin',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_plugins', to='home.subcategory'),
        ),
    ]
