# Generated by Django 5.2.7 on 2026-02-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_seed_plugin_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proplugin',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='proplugin',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='pro_plugins', to='home.subcategory'),
        ),
    ]
