# Generated by Django 5.2.7 on 2026-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_proplugin_subcategory_proplugin_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativeplugin',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='alternativeplugin',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='alt_plugins', to='home.subcategory'),
        ),
    ]
