# Generated by Django 5.2.7 on 2026-02-11 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_alternativeplugin_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('suggested_type', models.CharField(choices=[('PRO', 'Pro Plugin (VST/DAW)'), ('ALT', 'Free/Alternative Plugin')], default='ALT', max_length=3)),
                ('link', models.URLField(help_text='Official website or download link')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('date_suggested', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
