# Generated by Django 5.2.7 on 2026-04-15 19:26

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_pluginsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodemo',
            name='audio_file',
            field=models.FileField(upload_to='audio_demos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg']), home.models.validate_audio_size]),
        ),
    ]
