# Generated by Django 5.2.7 on 2026-04-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_audiodemo_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodemo',
            name='alt_plugin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_demos', to='home.alternativeplugin'),
        ),
    ]
